# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 823f935faf210f862208ae1bee347114130c27dc48fef17c90b7f37da34b2662ccb9fbde2bcf3d3130d6258bd64c1d53001a5bb95c23f754d889e8b4b77e0b21

test:
  secret_key_base: 31a7915bfe3162e501ba3a6abec5565da4ae830b17638531f1d4b0302a49950ac826ec008a02be51f8c55932330b30e13f40e8700903382c94d6fad1ec85b27f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
